language: go

go:
  - "1.x"
  - "1.2.x"
  - "1.3.x"
  - "1.4.x"
  - "1.5.x"
  - "1.9.x"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

before_install:
  - go get -t -v ./...

script:
  - go test

after_success:
  - bash <(curl -s https://codecov.io/bash)
